### ISSUE TITLE
jstree: add new node column

### ISSUE THREAD

**Issue by jonasjonas** [depage/depage-cms#2]
test new node column on firefox (and IE8/9 if possible)
On Firefox, it seems that there is a problem with z-index or something related, so that you cannot click on the buttons, because it disappears.

**Comment by dodiaraculus17** [comment]
**Sorry about Advertising**

I need contributors for my project. If you would like to help the project is located here.
https://github.com/poKe-Websites/poKe-CMS

Thank You :)
